lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' #required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' #required for token verifcation
    pass_phrase: '%env(JWT_PASSPHRASE)%' #required for token creation
    token_ttl: 10000 # in seconds, default is 3600
